import { pool } from "../config/database";
import {
  checkPageBreak,
  createPdfDocument,
  sanitizeFilename,
  sendPdfBuffer,
} from "./pdf.service";
import { getSubjectWithRelationsById } from "./subject.service";
import { listUnitsBySubject } from "./academicContent.service";

/* -------------------------------------------------------------------------- */
/* Types                                                                      */
/* -------------------------------------------------------------------------- */

interface QBRow {
  id: string;
  unit_id: string | null;
  question_text: string;
  marks: number;
  bloom_level: string | null;
  created_at: string;
}

export interface QuestionBankPdfResult {
  buffer: Buffer;
  filename: string;
}

/* -------------------------------------------------------------------------- */
/* Private helpers                                                            */
/* -------------------------------------------------------------------------- */

/** Roman numeral map for semester numbers 1–10. */
function toRoman(value: number): string {
  const map: Record<number, string> = {
    1: "I",
    2: "II",
    3: "III",
    4: "IV",
    5: "V",
    6: "VI",
    7: "VII",
    8: "VIII",
    9: "IX",
    10: "X",
  };
  return map[value] ?? String(value);
}

/** Returns the printable content width for the current page. */
function getContentWidth(doc: PDFKit.PDFDocument): number {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right;
}

/**
 * Renders a single question line (numbered) followed by the Bloom level tag.
 */
function renderQuestion(
  doc: PDFKit.PDFDocument,
  num: number,
  question: QBRow,
  contentWidth: number
): void {
  checkPageBreak(doc, 60);
  doc
    .font("Times-Roman")
    .fontSize(10.5)
    .fillColor("black")
    .text(`${num}. ${question.question_text}`, {
      width: contentWidth,
      lineBreak: true,
    });

  const bloomLabel = question.bloom_level ?? "N/A";
  doc
    .font("Times-Roman")
    .fontSize(9)
    .fillColor("#444444")
    .text(`(Bloom Level: ${bloomLabel})`, {
      width: contentWidth,
      lineBreak: false,
    });

  // 6pt gap after the bloom tag
  doc.fillColor("black").moveDown(6 / 9);
}

/**
 * Renders a part label (PART A / PART B / PART C) followed by its questions.
 */
function renderPart(
  doc: PDFKit.PDFDocument,
  label: string,
  questions: QBRow[],
  contentWidth: number
): void {
  checkPageBreak(doc, 80);
  doc
    .font("Times-Bold")
    .fontSize(11)
    .fillColor("black")
    .text(label, { width: contentWidth });

  // 14pt gap after part label
  doc.moveDown(14 / 11);

  questions.forEach((q, index) => {
    renderQuestion(doc, index + 1, q, contentWidth);
  });
}

/**
 * Writes the custom footer on every page using the bufferPages+switchToPage
 * pattern — identical to addPageNumbers() in pdf.service.ts but with
 * faculty name and generated date appended.
 */
function addQuestionBankFooter(
  doc: PDFKit.PDFDocument,
  facultyName: string
): void {
  const range = doc.bufferedPageRange();
  const today = new Date();
  const dd = String(today.getDate()).padStart(2, "0");
  const mm = String(today.getMonth() + 1).padStart(2, "0");
  const yyyy = today.getFullYear();
  const dateStr = `${dd}-${mm}-${yyyy}`;

  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);

    const originalBottom = doc.page.margins.bottom;
    // Suppress auto page-break while drawing in the physical margin area
    doc.page.margins.bottom = 0;

    const footerY = doc.page.height - 28;
    const w = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    doc
      .font("Times-Roman")
      .fontSize(8)
      .fillColor("#444444")
      .text(
        `Page ${i + 1} of ${range.count}  |  Generated by: ${facultyName}  |  Generated Date: ${dateStr}`,
        doc.page.margins.left,
        footerY,
        {
          width: w,
          align: "center",
          lineBreak: false,
        }
      )
      .fillColor("black");

    doc.page.margins.bottom = originalBottom;
  }
}

/**
 * Mirrors finalizePdf() from pdf.service.ts but calls addQuestionBankFooter
 * instead of addPageNumbers so the custom footer is used throughout.
 */
function finalizeWithCustomFooter(
  doc: PDFKit.PDFDocument,
  facultyName: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    addQuestionBankFooter(doc, facultyName);
    doc.end();
  });
}

/* -------------------------------------------------------------------------- */
/* Main export                                                                */
/* -------------------------------------------------------------------------- */

export async function generateQuestionBankPdf(
  subjectId: string,
  unitId: string | undefined,
  facultyName: string
): Promise<QuestionBankPdfResult> {
  /* ---------------------------------------------------------------------- */
  /* 1. Fetch subject metadata                                               */
  /* ---------------------------------------------------------------------- */
  const subject = await getSubjectWithRelationsById(subjectId);

  const subjectCode =
    subject?.subject_code?.trim() || "Unknown";

  const subjectName =
    subject?.subject_name?.trim() || "Not Specified";

  const departmentName =
    subject?.department_name?.trim() || "Not Specified";

  const academicYearName =
    (subject as any)?.academic_year_name?.trim() || "Not Specified";

  const semesterNumber: number | null =
    (subject as any)?.semester_number ?? null;

  const semesterLabel =
    semesterNumber !== null ? toRoman(semesterNumber) : "Not Specified";

  const safeSubjectCode = subjectCode === "Unknown" ? "Unknown" : subjectCode;

  /* ---------------------------------------------------------------------- */
  /* 2. Fetch units and approved+active questions                            */
  /* ---------------------------------------------------------------------- */
  const units = await listUnitsBySubject(subjectId);

  const queryValues: unknown[] = [subjectId];
  let unitFilter = "";
  if (unitId !== undefined) {
    queryValues.push(unitId);
    unitFilter = ` AND unit_id = $${queryValues.length}`;
  }

  const questionsResult = await pool.query<QBRow>(
    `SELECT id, unit_id, question_text, marks, bloom_level, created_at
     FROM question_bank
     WHERE subject_id = $1
       AND is_approved = TRUE
       AND is_active = TRUE${unitFilter}
     ORDER BY marks ASC, created_at ASC`,
    queryValues
  );

  const questions: QBRow[] = questionsResult.rows;

  /* ---------------------------------------------------------------------- */
  /* 3. Create PDF document                                                  */
  /* ---------------------------------------------------------------------- */
  const doc = createPdfDocument();
  const contentWidth = getContentWidth(doc);

  /* ---------------------------------------------------------------------- */
  /* 4. Running header for pages 2+ (registered before any content is drawn)*/
  /* ---------------------------------------------------------------------- */
  doc.on("pageAdded", () => {
    const left = doc.page.margins.left;
    const w = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    doc
      .font("Times-Roman")
      .fontSize(8)
      .fillColor("#666666")
      .text(
        `RAMCO INSTITUTE OF TECHNOLOGY (Autonomous) | Question Bank \u2013 ${subjectCode} ${subjectName}`,
        left,
        doc.page.margins.top - 20,
        {
          width: w,
          align: "left",
          lineBreak: false,
        }
      )
      .fillColor("black");
    // Reset content cursor below the running header
    doc.y = doc.page.margins.top + 5;
  });

  /* ---------------------------------------------------------------------- */
  /* 5. First-page institutional header (mirrors reference exam-paper style)*/
  /* ---------------------------------------------------------------------- */
  const left = doc.page.margins.left;

  // Row 1: College name — Times-Bold 16pt, centered
  doc
    .font("Times-Bold")
    .fontSize(16)
    .fillColor("black")
    .text("RAMCO INSTITUTE OF TECHNOLOGY", left, doc.y, {
      width: contentWidth,
      align: "center",
    });

  // Row 2: Autonomous designation — Times-Bold 10.5pt, centered
  doc
    .font("Times-Bold")
    .fontSize(10.5)
    .text("AN AUTONOMOUS INSTITUTE", left, doc.y + 1, {
      width: contentWidth,
      align: "center",
    });

  // Row 3: Department — Times-Bold 11.5pt, centered, uppercase
  const deptFormatted = /^department\s+of\s+/i.test(departmentName)
    ? departmentName.toUpperCase()
    : `DEPARTMENT OF ${departmentName.toUpperCase()}`;

  doc
    .font("Times-Bold")
    .fontSize(11.5)
    .text(deptFormatted, left, doc.y + 1, {
      width: contentWidth,
      align: "center",
    });

  // Row 4: Academic year — Times-Bold 11pt, centered
  if (academicYearName !== "Not Specified") {
    doc
      .font("Times-Bold")
      .fontSize(11)
      .text(`ACADEMIC YEAR (${academicYearName})`, left, doc.y + 1, {
        width: contentWidth,
        align: "center",
      });
  }

  // Row 5: "QUESTION BANK" — Times-Bold 12pt, centered
  //         (same visual weight as "INTERNAL ASSESSMENT TEST - I" in reference)
  doc
    .font("Times-Bold")
    .fontSize(12)
    .text("QUESTION BANK", left, doc.y + 1, {
      width: contentWidth,
      align: "center",
    });

  doc.moveDown(0.3);

  // Subject info rows — two-column layout matching reference
  // Left column: Semester/Branch + Faculty Name + Subject Code + Subject Name
  // (No Date, Time, or Max. Marks for a Question Bank document)
  const infoWidth = contentWidth;
  const y1 = doc.y;

  doc.font("Times-Bold").fontSize(10.2);

  const semesterAndBranch =
    semesterNumber !== null
      ? `${semesterLabel} Semester / ${departmentName}`
      : departmentName;

  const semesterText = `Semester and Branch: ${semesterAndBranch}`;
  doc.text(semesterText, left, y1, { width: infoWidth });

  const h1 = doc.heightOfString(semesterText, { width: infoWidth });
  const y2 = y1 + Math.max(h1, 12) + 1;

  const facultyText = `Faculty Name: ${facultyName || "________________"}`;
  doc.text(facultyText, left, y2, { width: infoWidth });

  const h2 = doc.heightOfString(facultyText, { width: infoWidth });
  const y3 = y2 + Math.max(h2, 12) + 1;

  const displaySubjectCode = subjectCode === "Unknown" ? "Not Specified" : subjectCode;
  doc.text(`Subject Code: ${displaySubjectCode}`, left, y3, { width: infoWidth });

  const h3 = doc.heightOfString(`Subject Code: ${displaySubjectCode}`, { width: infoWidth });
  const y4 = y3 + Math.max(h3, 12) + 1;

  doc.text(`Subject Name: ${subjectName}`, left, y4, { width: infoWidth });

  const h4 = doc.heightOfString(`Subject Name: ${subjectName}`, { width: infoWidth });
  doc.y = y4 + Math.max(h4, 12) + 4;

  // Horizontal rule separating header from question-bank content
  doc.moveDown(0.3);
  doc
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(0.6);

  /* ---------------------------------------------------------------------- */
  /* 6. Unit-wise question sections                                          */
  /* ---------------------------------------------------------------------- */
  for (const unit of units) {
    const unitQuestions = questions.filter((q) => q.unit_id === unit.id);

    // Skip units with no approved+active questions for this filter
    if (unitQuestions.length === 0) continue;

    // Unit heading
    checkPageBreak(doc, 80);
    doc
      .font("Times-Bold")
      .fontSize(12)
      .fillColor("black")
      .text(
        `UNIT ${toRoman(unit.unit_number)} \u2013 ${unit.unit_title.toUpperCase()}`,
        { width: contentWidth }
      );
    // 14pt gap after unit heading
    doc.moveDown(14 / 12);

    // Partition by marks
    const partA = unitQuestions.filter((q) => q.marks === 2);
    const partB = unitQuestions.filter((q) => q.marks === 16);
    const otherMarkValues = [
      ...new Set(
        unitQuestions
          .filter((q) => q.marks !== 2 && q.marks !== 16)
          .map((q) => q.marks)
      ),
    ].sort((a, b) => a - b);

    if (partA.length > 0) {
      renderPart(doc, "PART A \u2013 2 MARK QUESTIONS", partA, contentWidth);
    }
    if (partB.length > 0) {
      renderPart(doc, "PART B \u2013 16 MARK QUESTIONS", partB, contentWidth);
    }
    for (const m of otherMarkValues) {
      const partC = unitQuestions.filter((q) => q.marks === m);
      renderPart(doc, `PART C \u2013 ${m} MARK QUESTIONS`, partC, contentWidth);
    }
  }

  /* ---------------------------------------------------------------------- */
  /* 7. Empty state                                                          */
  /* ---------------------------------------------------------------------- */
  if (questions.length === 0) {
    doc
      .font("Times-Roman")
      .fontSize(10)
      .fillColor("black")
      .text("No questions found for the selected filter.", {
        align: "center",
        width: contentWidth,
      });
  }

  /* ---------------------------------------------------------------------- */
  /* 8. Finalize with custom footer and return                               */
  /* ---------------------------------------------------------------------- */
  const buffer = await finalizeWithCustomFooter(doc, facultyName);

  const safeSubjectName = sanitizeFilename(subjectName);
  const filename = `QuestionBank_${safeSubjectCode}_${safeSubjectName}`;

  return { buffer, filename };
}
